server:
  port: 8084

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/paymentsdb

  kafka:
    bootstrap-servers: localhost:9090,localhost:9091,localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
        enable:
          idempotence: true
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.ryzend.kafka.*

topics:
  payment:
    events:
      name: payment-events
    commands:
      name: payment-commands